runtime: nodejs14

handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /images
    static_dir: images

  - url: /logout
    script: auto

  - url: /homepage
    static_files: homepage.html
    upload: homepage.html

  - url: /
    static_files: index.html
    upload: index.html